/* DATA CORRECTIONS */
(() => {
  const DATA = window.BUCANEVE_DATA || window.LUNO_DATA || window.SITE_DATA || window.WORKS_DATA || null;
  if (!DATA || !Array.isArray(DATA.works)) return;

  const underworld = Array.isArray(DATA.categories)
    ? DATA.categories.find(category => typeof category === "string" ? category === "裏社会" : category?.name === "裏社会" || category?.id === "裏社会") : null;
  const underworldId = typeof underworld === "string" ? underworld : underworld?.id || "裏社会";
  const regular = DATA.works.find(work => String(work?.id || "").trim() === "dangerous-regular"); if (regular) regular.category = underworldId;
  const fixes=[['summer-not-enough','2026.08.03'],['hello-my-lover','2026.08.07'],['boss-obey-me','2026.08.08'],['white-serpent-bed','2026.08.10'],['same-podium','2026.08.12']];
  fixes.forEach(([id,date])=>{const w=DATA.works.find(x=>String(x?.id||'')===id);if(w){w.status='published';w.isNew=false;w.releaseDate=date;}});
})();

(() => {
  "use strict";
  document.querySelectorAll(".reveal").forEach(el => el.classList.add("is-visible"));
  const gate=document.getElementById("gate"),site=document.getElementById("site");
  function enter(){gate?.classList.add("is-leaving");site?.classList.remove("is-hidden");try{sessionStorage.setItem("lunoEntered","1")}catch(_){}}
  document.getElementById("enterBtn")?.addEventListener("click",enter);document.getElementById("skipBtn")?.addEventListener("click",enter);try{if(sessionStorage.getItem("lunoEntered")==="1")enter()}catch(_){}
  const DATA=window.BUCANEVE_DATA||window.LUNO_DATA||window.SITE_DATA||window.WORKS_DATA||null;
  const archiveCount=document.getElementById("archiveCount"),workArea=document.getElementById("workArea"),filters=document.getElementById("filters"),newsList=document.getElementById("newsList"),dialog=document.getElementById("workDialog"),searchInput=document.getElementById("workSearch"),clearSearch=document.getElementById("clearSearch"),resultCount=document.getElementById("resultCount");
  const menu=document.getElementById("menuBtn"),nav=document.getElementById("nav");let menuCloseTimer=null;
  function setMenu(open){if(!nav||!menu)return;clearTimeout(menuCloseTimer);if(open){nav.hidden=false;requestAnimationFrame(()=>nav.classList.add("open"));document.body.classList.add("menu-open")}else{nav.classList.remove("open");document.body.classList.remove("menu-open");menuCloseTimer=setTimeout(()=>{if(!nav.classList.contains("open"))nav.hidden=true},360)}menu.classList.toggle("is-open",open);menu.setAttribute("aria-expanded",String(open));}
  if(nav&&!nav.classList.contains("open"))nav.hidden=true;menu?.addEventListener("click",()=>setMenu(!nav?.classList.contains("open")));nav?.addEventListener("click",e=>{if(e.target.closest("a"))setMenu(false)});
  const topBtn=document.getElementById("backToTop");window.addEventListener("scroll",()=>topBtn?.classList.toggle("show",window.scrollY>700));topBtn?.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
  if(!DATA||!Array.isArray(DATA.works)){if(workArea)workArea.innerHTML='<div class="empty-state">作品データを読み込めませんでした。</div>';return}
  const categories=Array.isArray(DATA.categories)?DATA.categories:[],seriesItems=Array.isArray(DATA.series)?DATA.series:[];
  const CATS=Object.fromEntries(categories.map(c=>[typeof c==='string'?c:c.id,typeof c==='string'?c:c.name]));const SERIES=Object.fromEntries(seriesItems.map(s=>[typeof s==='string'?s:s.id,typeof s==='string'?s:s.name]));const STATUS={published:'公開中',draft:'未公開'};let activeCategory='all';
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const cat=w=>CATS[w.category]||w.category||'その他';const ser=w=>(w.series&&SERIES[w.series])||(w.world&&SERIES[w.world])||'';const searchable=w=>[w.title,w.description,cat(w),ser(w),...(w.tags||[])].join(' ').toLowerCase();
  const normalizeSeriesName=w=>{const n=String(ser(w)||'').trim();if(n==='カスティリオーネ'||n==='フェローネ')return 'カスティリオーネ／フェローネ';return n};
  const workPriority=w=>w.isNew&&w.status!=='draft'?0:w.status!=='draft'?1:2;const sortWorksInsideGroup=list=>[...list].sort((a,b)=>workPriority(a)-workPriority(b)||String(b.releaseDate||'').localeCompare(String(a.releaseDate||''),'ja'));
  function revealWorkCards(scope=document){[...scope.querySelectorAll('.work-card')].forEach((c,i)=>setTimeout(()=>c.classList.add('is-card-visible'),Math.min(i*45,360)))}
  if(archiveCount)archiveCount.textContent=`${DATA.works.length} WORKS`;
  function renderFilters(){if(!filters)return;const items=[{id:'all',name:'すべて'},...categories.map(c=>typeof c==='string'?{id:c,name:c}:c),{id:'draft',name:'未公開'}];filters.innerHTML=items.map((x,i)=>`<button class="filter-btn ${i===0?'active':''}" data-category="${esc(x.id)}">${esc(x.name)}</button>`).join('');filters.addEventListener('click',e=>{const b=e.target.closest('.filter-btn');if(!b)return;activeCategory=b.dataset.category;filters.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderWorks()})}
  function belongs(w,id){if(String(w.category||'')===id||String(w.series||'')===id||String(w.world||'')===id)return true;const s=seriesItems.find(x=>typeof x!=='string'&&String(x?.id||'')===id);return Array.isArray(s?.works)&&s.works.includes(String(w.id||''))}
  function filteredWorks(){const q=(searchInput?.value||'').trim().toLowerCase();return DATA.works.filter(w=>(activeCategory==='all'||(activeCategory==='draft'?w.status==='draft':belongs(w,activeCategory)))&&(!q||searchable(w).includes(q)))}
  function cardHtml(w,index){const draft=w.status==='draft',title=draft?'TITLE CLASSIFIED':w.title,status=draft?'UNRELEASED':'NOW AVAILABLE';return `<article class="work-card ${draft?'is-draft':'is-published'} ${w.isNew?'is-new':''}" data-id="${esc(w.id)}" ${draft?'aria-disabled="true"':`tabindex="0" role="button"`}><div class="work-visual" style="--cover:url('${esc(w.cover||'')}')"><span class="work-number">${String(index+1).padStart(2,'0')}</span><span class="work-status-ribbon">${status}</span>${w.isNew&&!draft?'<span class="work-new-badge">NEW RELEASE</span>':''}</div><div class="work-body"><div class="work-card-topline"><span class="work-category">${esc(ser(w)||cat(w))}</span><span class="work-status-dot">${draft?'非公開':esc(STATUS[w.status]||'')}</span></div><h3>${esc(title)}</h3><p class="work-card-description">${esc(draft?'作品情報は公開時に解禁されます。':w.description||'')}</p><div class="work-meta"><span>${esc(cat(w))}</span><span class="work-detail-link">${draft?'LOCKED':'VIEW STORY <i>↗</i>'}</span></div></div></article>`}
  function renderWorks(){if(!workArea)return;const items=filteredWorks();if(resultCount)resultCount.textContent=`${items.length}作品`;if(!items.length){workArea.innerHTML='<div class="empty-state">該当する作品が見つかりませんでした。</div>';return}workArea.innerHTML=`<div class="work-grid gallery-grid">${sortWorksInsideGroup(items).map(cardHtml).join('')}</div>`;revealWorkCards(workArea)}
  searchInput?.addEventListener('input',renderWorks);clearSearch?.addEventListener('click',()=>{if(searchInput){searchInput.value='';renderWorks()}});
  function openWork(w){if(!dialog||!w||w.status==='draft')return;const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v||''};document.getElementById('dialogVisual')?.style.setProperty('--cover',`url('${w.cover||''}')`);set('dialogTitle',w.title);set('dialogCategory',ser(w)||cat(w));set('dialogStatus',STATUS[w.status]);set('dialogCatch',w.catchphrase||w.catch||'');set('dialogSummary',w.description||'');const actions=document.getElementById('dialogActions'),link=w.url||w.link||w.zetaUrl||w.zeta||'';if(actions)actions.innerHTML=(link?`<a class="button story-primary-action" href="${esc(link)}">READ <span>→</span></a>`:'')+'<button class="button story-secondary-action" type="button" id="dialogBack">作品一覧へ戻る</button>';document.getElementById('dialogBack')?.addEventListener('click',()=>dialog.close());dialog.showModal();requestAnimationFrame(()=>dialog.classList.add('is-story-open'))}
  workArea?.addEventListener('click',e=>{const c=e.target.closest('.work-card');if(!c)return;const w=DATA.works.find(x=>String(x.id)===c.dataset.id);if(w&&w.status!=='draft')openWork(w)});document.getElementById('closeDialog')?.addEventListener('click',()=>dialog?.close());dialog?.addEventListener('close',()=>dialog.classList.remove('is-story-open'));
  try{renderFilters();renderWorks()}catch(e){console.error(e);if(workArea)workArea.innerHTML='<div class="empty-state">作品一覧の表示中にエラーが発生しました。</div>'}
})();

(() => {const overlay=document.getElementById('pageTransition');const show=()=>requestAnimationFrame(()=>{document.body.classList.add('page-ready');overlay?.classList.remove('is-active')});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',show,{once:true});else show();window.addEventListener('pageshow',show);document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a||!overlay)return;const href=a.getAttribute('href');if(!href||href.startsWith('#')||href.startsWith('mailto:')||href.startsWith('tel:')||a.target==='_blank'||a.hasAttribute('download'))return;const d=new URL(a.href,location.href);if(d.origin!==location.origin)return;e.preventDefault();document.body.classList.remove('page-ready');overlay.classList.add('is-active');setTimeout(()=>location.href=d.href,280)})})();

(() => {const targets=document.querySelectorAll('.home-scroll-reveal');if(!targets.length)return;if(!('IntersectionObserver'in window)){targets.forEach(x=>x.classList.add('is-visible'));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');o.unobserve(e.target)}}),{threshold:.16});targets.forEach(x=>o.observe(x))})();

document.addEventListener('click',e=>{const link=e.target.closest('[data-link-placeholder]');if(link)e.preventDefault()});

(() => {const cards=[...document.querySelectorAll('[data-world-card]')];cards.forEach(card=>card.querySelector('.world-portal-visual')?.addEventListener('click',()=>{const open=!card.classList.contains('is-open');cards.forEach(x=>x.classList.remove('is-open'));if(open)card.classList.add('is-open')}))})();