window.BUCANEVE_DATA = {
  "site": {
    "name": "Bucaneve Archive",
    "language": "ja",
    "publishedCount": 52,
    "draftCount": 7
  },
  "categories": [
    {
      "id": "euphoria",
      "name": "Euphoria"
    },
    {
      "id": "fantasy",
      "name": "Fantasy"
    },
    {
      "id": "modern-romance",
      "name": "現代・恋愛"
    },
    {
      "id": "underworld",
      "name": "裏社会"
    },
    {
      "id": "keigaku",
      "name": "零学"
    }
  ],
  "series": [
    {
      "id": "euphoria",
      "name": "Euphoria",
      "type": "series",
      "works": [
        "whichever-you-trust-no-escape",
        "sweet-collapse",
        "violet-dependence",
        "code-requiem",
        "nocturne-code",
        "crimson-silence",
        "lilium-dependence"
      ]
    },
    {
      "id": "astrain-kingdom",
      "name": "アストレイン王国",
      "type": "shared-world",
      "works": [
        "holy-knight-childhood-friend",
        "strongest-childhood-friend"
      ]
    },
    {
      "id": "castiglione-felone",
      "name": "カスティリオーネ／フェローネ",
      "type": "shared-world",
      "works": [
        "castiglione-treasure",
        "doctor-felone-heart"
      ]
    },
    {
      "id": "valentino",
      "name": "ヴァレンティノ",
      "type": "series",
      "works": [
        "embers-lie",
        "gunpowder-rain",
        "sunlight-vow"
      ]
    },
    {
      "id": "keigaku",
      "name": "零学",
      "type": "series",
      "works": [
        "keigaku-arsene",
        "keigaku-adrian"
      ]
    }
  ],
  "works": [
    {
      "id": "whichever-you-trust-no-escape",
      "title": "どちらを信じても、逃げられない。",
      "status": "draft",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "MULTI STORY",
      "mainCharacter": "久瀬紫苑／九条碧",
      "relation": ["久瀬紫苑", "九条碧"],
      "cover": "images/covers/whichever-you-trust-no-escape.jpeg",
      "coverStatus": "ready",
      "isNew": false,
      "catchphrase": "どちらを信じても、逃げられない。",
      "tags": ["潜入捜査", "バディ", "三人チーム", "心理戦", "信頼", "関係変化"],
      "description": "巨大歓楽街《ノクス区》の地下で、静かに流通を広げる新型ドラッグ《Euphoria》。感情や依存心を異常増幅させる危険薬物でありながら、その製造元も流通経路も、いまだ掴めていない。紫京厚生局麻薬取締部に所属する{{user}}は、同期の麻薬取締官・久瀬紫苑と九条碧と共に身分を偽り、ノクス区への潜入捜査を開始する。笑顔の裏に本心を隠し、相手の懐へ入り込む紫苑。沈黙と観察によって、わずかな違和感も見逃さない碧。長年相棒として現場を共にしてきた二人は、互いの能力を信頼している。だが、捜査への考え方も、{{user}}への接し方も同じではない。情報収集、張り込み、聞き込み、証拠整理。三人で任務を重ねるほど、捜査だけでは割り切れない感情が静かに形を変えていく。追うべきものは、薬物の流通経路。信じるべきものは、二人の言葉。けれどノクス区では、信頼さえも利用される。"
    },
    {
      "id": "sweet-collapse",
      "title": "Sweet Collapse",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/sweet-collapse.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "gods-wont-go-home",
      "title": "神様たちが帰ってくれません！",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/gods-wont-go-home.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "contract-bride",
      "title": "契約満了まで、俺の花嫁。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/contract-bride.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "snake-god-sleepless",
      "title": "蛇神様と、朝まで眠れない。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/snake-god-sleepless.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "dangerous-regular",
      "title": "危険な常連客",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/dangerous-regular.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "too-cute-student",
      "title": "可愛すぎる僕の、可愛くない先生",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/too-cute-student.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "unchosen-sister",
      "title": "選ばれなかった姉は、隣国で愛を知る",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/unchosen-sister.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "five-stars",
      "title": "五人の星は、君を選ぶ。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/five-stars.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "crow-marriage",
      "title": "鴉との婚姻",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/crow-marriage.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "embers-lie",
      "title": "残り火に、君の嘘を見た",
      "status": "published",
      "category": "fantasy",
      "series": "valentino",
      "world": "valentino",
      "position": "main",
      "mainCharacter": "カイン・ヴァレンティノ",
      "relation": [
        "ディラン・ヴァレンティノ（弟）",
        "追憶：陽だまりの誓い（スピンオフ）"
      ],
      "cover": "images/covers/embers-lie.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "berry-vamp",
      "title": "Berry×Vamp",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/berry-vamp.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "forget-you-save-world",
      "title": "あなたを忘れる日、世界が救われる",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/forget-you-save-world.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "stellar-academy",
      "title": "STELLAR ACADEMY",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/stellar-academy.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "violet-dependence",
      "title": "VIOLET DEPENDENCE",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "SOLO STORY",
      "mainCharacter": "久瀬紫苑",
      "relation": ["久瀬紫苑"],
      "cover": "images/covers/violet-dependence.jpeg",
      "coverStatus": "ready",
      "catchphrase": "この感情は、本物か。それとも《Euphoria》が生んだ依存か。",
      "tags": ["潜入捜査", "偽装恋人", "バディ", "監視役", "EDEN", "愛と依存"],
      "description": "巨大歓楽街《ノクス区》の裏で、新型ドラッグ《Euphoria》が密かに流通していた。感情や依存心を異常に増幅させ、特定の誰かなしでは正常な精神を保てなくする危険薬物。その製造元と流通組織を壊滅させるため、紫京厚生局麻薬取締部は極秘潜入作戦を開始する。{{user}}は、突出した潜入能力を持つ一方で命令違反や単独行動も辞さない麻薬取締官・久瀬紫苑と、初めて正式なバディを組む。表向きの身分は恋人。だが{{user}}には、紫苑の相棒であると同時に監視役として同行する任務も課されていた。情報屋との接触、違法クラブへの潜入、売人の追跡を重ねるうち、二人は巨大犯罪組織《EDEN》の存在へ辿り着く。互いの命を預け合うほど信頼は深まり、偽りだった恋人関係も演技では済まされなくなっていく。しかし、その想いが自分自身の意思なのか、《Euphoria》が生んだ依存なのか、二人にはもう分からない。正義を貫くのか。それとも、愛と依存の境界が崩れた先へ堕ちるのか。誰にも知られてはならない潜入任務は続いていく。"
    },
    {
      "id": "castiglione-treasure",
      "title": "カスティリオーネの至宝は四人に溺愛される",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": "castiglione-felone",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/castiglione-treasure.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "strangers-at-work-lovers-at-home",
      "title": "会社では他人。家では恋人。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/strangers-at-work-lovers-at-home.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "absolute-zero-dom",
      "title": "絶対零度のDomは愛し子にだけ溶ける",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/absolute-zero-dom.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "hualong-princess",
      "title": "華龍会のお姫様になりました。",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/hualong-princess.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "only-mean-to-you",
      "title": "全員、君にだけ意地悪。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/only-mean-to-you.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "day-and-night",
      "title": "昼と夜は、君を譲らない。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/day-and-night.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "fox-waits-thousand-years",
      "title": "狐は千年、君を待つ",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/fox-waits-thousand-years.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "alf-layla",
      "title": "千夜一恋譚 ～アルフ・ライラ～",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/alf-layla.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "wicked-lady-black-wolf",
      "title": "悪女と黒狼公爵の偽装夫婦事情",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/wicked-lady-black-wolf.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "code-requiem",
      "title": "CODE: REQUIEM",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/code-requiem.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "angel-and-four-devils",
      "title": "天界から逃げた天使は、四人の悪魔に拾われる。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/angel-and-four-devils.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "perfect-coworker-secret-account",
      "title": "完璧な同期は、裏垢男子。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/perfect-coworker-secret-account.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "sougetsurou",
      "title": "絢爛たる双月楼",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/sougetsurou.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "gunpowder-rain",
      "title": "硝煙は、雨の日の君の香りがした",
      "status": "published",
      "category": "fantasy",
      "series": "valentino",
      "world": "valentino",
      "position": "main",
      "mainCharacter": "ディラン・ヴァレンティノ",
      "relation": [
        "カイン・ヴァレンティノ（兄）"
      ],
      "cover": "images/covers/gunpowder-rain.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "doctor-felone-heart",
      "title": "白衣の先生は、フェローネの心臓。",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": "castiglione-felone",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/doctor-felone-heart.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "lunacales",
      "title": "依存の庭、ルナカレス",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/lunacales.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "greedy-wolf-white-rabbit",
      "title": "強欲な狼は白兎を愛でる",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/greedy-wolf-white-rabbit.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "holy-knight-childhood-friend",
      "title": "聖騎士団長は“幼馴染み”をやめたい",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": "astrain-kingdom",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/holy-knight-childhood-friend.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "four-vampires",
      "title": "四人の吸血鬼は、君を離さない。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/four-vampires.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "keigaku-arsene",
      "title": "【零学】アルセイン・ルヴェリエ",
      "status": "published",
      "category": "keigaku",
      "series": "keigaku",
      "world": "keigaku",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/keigaku-arsene.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "nocturne-code",
      "title": "NOCTURNE CODE",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/nocturne-code.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "crimson-silence",
      "title": "CRIMSON SILENCE",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/crimson-silence.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "saint-quits",
      "title": "聖女、辞めます。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/saint-quits.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "fox-does-not-love-humans",
      "title": "狐は人間を愛さない",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/fox-does-not-love-humans.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "star-lamp-in-abyss",
      "title": "深淵に沈む星灯",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/star-lamp-in-abyss.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "frontier-count-mate",
      "title": "逃がした番を取り戻したい辺境伯の話",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/frontier-count-mate.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "strongest-childhood-friend",
      "title": "世界最強の幼馴染は、落ちこぼれしか見ていない。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": "astrain-kingdom",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/strongest-childhood-friend.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "hide-and-cat",
      "title": "ハイド・アンド・キャット",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/hide-and-cat.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "lilium-dependence",
      "title": "Lilium Dependence",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/lilium-dependence.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "keigaku-adrian",
      "title": "【零学】アドリアン・ヴァルハルト",
      "status": "published",
      "category": "keigaku",
      "series": "keigaku",
      "world": "keigaku",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/keigaku-adrian.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "code-scarlet",
      "title": "CODE SCARLET",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/code-scarlet.jpeg",
      "coverStatus": "ready",
      "tags": [
        "現代",
        "警察官"
      ],
      "description": ""
    },
    {
      "id": "emperor-body-pillow",
      "title": "皇帝の抱き枕係に任命されました。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/emperor-body-pillow.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "senpai-forbidden-tonight",
      "title": "今夜だけは、先輩禁止。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/senpai-forbidden-tonight.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "kiss-order-violation",
      "title": "その口づけは、命令違反。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/kiss-order-violation.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "sunlight-vow",
      "title": "追憶：陽だまりの誓い",
      "status": "published",
      "category": "fantasy",
      "series": "valentino",
      "world": "valentino",
      "position": "spin-off",
      "mainCharacter": "カイン・ヴァレンティノ",
      "relation": [
        "残り火に、君の嘘を見た（本編）"
      ],
      "cover": "images/covers/sunlight-vow.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "no1-jealousy",
      "title": "No.1の嫉妬は、営業じゃない。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/no1-jealousy.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "say-you-like-me",
      "title": "好きならそう言えよ、同期くん。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/say-you-like-me.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "love-meter-max",
      "title": "愛情値、限界突破中。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/love-meter-max.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "hello-my-lover",
      "title": "初めまして、俺の恋人。",
      "status": "draft",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/hello-my-lover.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "same-podium",
      "title": "俺たちは、同じ表彰台に立てない。",
      "status": "draft",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/same-podium.jpeg",
      "coverStatus": "ready",
      "tags": [
        "現代",
        "フィギュアスケート",
        "BL"
      ],
      "description": ""
    },
    {
      "id": "hated-actor",
      "title": "嫌われ俳優は、君の前でだけ演じない。",
      "status": "draft",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/hated-actor.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "black-dragon",
      "title": "黒龍は龍妃を認めない",
      "status": "draft",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/black-dragon.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "boss-obey-me",
      "title": "ボス、今夜は俺に従え。",
      "status": "draft",
      "category": "underworld",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/boss-obey-me.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "summer-not-enough",
      "title": "君と泳ぐには、夏が足りない。",
      "status": "draft",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/summer-not-enough.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    }
  ]
};
