window.BUCANEVE_DATA = {
  "site": {
    "name": "Bucaneve Archive",
    "language": "ja",
    "publishedCount": 52,
    "draftCount": 7
  },
  "categories": [
    {
      "id": "euphoria",
      "name": "Euphoria"
    },
    {
      "id": "fantasy",
      "name": "Fantasy"
    },
    {
      "id": "modern-romance",
      "name": "現代・恋愛"
    },
    {
      "id": "underworld",
      "name": "裏社会"
    },
    {
      "id": "keigaku",
      "name": "零学"
    }
  ],
  "series": [
    {
      "id": "euphoria",
      "name": "Euphoria",
      "type": "series",
      "works": [
        "whichever-you-trust-no-escape",
        "sweet-collapse",
        "violet-dependence",
        "code-requiem",
        "nocturne-code",
        "crimson-silence",
        "lilium-dependence"
      ]
    },
    {
      "id": "astrain-kingdom",
      "name": "アストレイン王国",
      "type": "shared-world",
      "works": [
        "holy-knight-childhood-friend",
        "strongest-childhood-friend"
      ]
    },
    {
      "id": "castiglione-felone",
      "name": "カスティリオーネ／フェローネ",
      "type": "shared-world",
      "works": [
        "castiglione-treasure",
        "doctor-felone-heart"
      ]
    },
    {
      "id": "valentino",
      "name": "ヴァレンティノ",
      "type": "series",
      "works": [
        "embers-lie",
        "gunpowder-rain",
        "sunlight-vow"
      ]
    },
    {
      "id": "keigaku",
      "name": "零学",
      "type": "series",
      "works": [
        "keigaku-arsene",
        "keigaku-adrian"
      ]
    }
  ],
  "works": [
    {
      "id": "whichever-you-trust-no-escape",
      "title": "どちらを信じても、逃げられない。",
      "status": "draft",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "MULTI STORY",
      "mainCharacter": "久瀬紫苑／九条碧",
      "relation": [
        "久瀬紫苑",
        "九条碧"
      ],
      "cover": "images/covers/whichever-you-trust-no-escape.jpeg",
      "coverStatus": "ready",
      "isNew": false,
      "catchphrase": "どちらを信じても、逃げられない。",
      "tags": [
        "潜入捜査",
        "バディ",
        "三人チーム",
        "心理戦",
        "信頼",
        "関係変化"
      ],
      "description": "巨大歓楽街《ノクス区》。\n\n眠らない街の地下では、\n新型ドラッグ《Euphoria》が静かに流通を広げている。\n\n感情や依存心を異常増幅させる危険薬物。\nその製造元も流通経路も、いまだ掴めていない。\n\n紫京厚生局麻薬取締部に所属する{{user}}は、\n同期の麻薬取締官・久瀬紫苑、九条碧と共に身分を偽り、\nノクス区への潜入捜査を開始する。\n\n笑顔の裏に本心を隠し、相手の懐へ入り込む紫苑。\n沈黙と観察によって、わずかな違和感も見逃さない碧。\n\n長年相棒として現場を共にしてきた二人は、\n互いの能力を信頼している。\n\nだが、捜査への考え方も、\n{{user}}への接し方も同じではない。\n\n情報収集、張り込み、聞き込み、証拠整理。\n三人で任務を重ねるほど、\n捜査だけでは割り切れない感情が静かに形を変えていく。\n\n追うべきものは、薬物の流通経路。\n信じるべきものは、二人の言葉。\n\nけれどノクス区では、\n信頼さえも利用される。"
    },
    {
      "id": "sweet-collapse",
      "title": "Sweet Collapse",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "SOLO STORY",
      "mainCharacter": "雪城ルイ",
      "relation": [
        "雪城ルイ"
      ],
      "cover": "images/covers/sweet-collapse.jpeg",
      "coverStatus": "ready",
      "tags": [
        "潜入捜査",
        "EDEN",
        "精神誘導",
        "偽りの信頼",
        "依存",
        "甘い破滅"
      ],
      "description": "巨大歓楽街《ノクス区》。\n\n政財界、海外マフィア、ドラッグカルテルが交錯する眠らない街で、\n新型ドラッグ《Euphoria》が静かに流通を広げていた。\n\n強烈な幸福感と引き換えに、\n特定の誰かへの依存を異常なまでに増幅させる危険薬物。\n\nその供給源を突き止めるため、\n紫京厚生局麻薬取締部は犯罪シンジケート《EDEN》への潜入捜査を開始する。\n\n任務を命じられた{{user}}が接触したのは、\nEDENの幹部――雪城ルイ。\nコードネーム《SERAPH》。\n\n組織内で勧誘と精神誘導を担い、\n暴力ではなく言葉と信頼によって人を支配する危険人物だった。\n\n初対面であるはずなのに、ルイは{{user}}を穏やかに迎え入れる。\nまるで、ずっと前から会うことを知っていたかのように。\n\n彼は会うたびに気遣い、傷を見つければ手当てをし、\n危険な任務の後には何も問わず隣へ座る。\n\n敵であるはずの男だけが、\n誰より早く{{user}}の心の揺らぎに気づいてしまう。\n\nけれど、その優しさこそがルイの最大の武器だった。\n否定せず、寄り添い、信頼を重ね、\nいつしか「この人だけは失いたくない」と思わせる。\n\n捜査が進むほどEDENの真実へ近づき、\n同時にルイとの距離も縮まっていく。\n\n正義を貫けば、彼を裏切ることになる。\n彼を信じれば、任務を裏切ることになる。\n\nEDENを壊すのか。\nそれとも、雪城ルイと共に甘い破滅を選ぶのか。\n\nその想いが潜入のための偽りだったのか、\n恋だったのかを知る頃には、もう戻れない。",
      "catchphrase": "その優しさは、救いではなく侵食だった。"
    },
    {
      "id": "gods-wont-go-home",
      "title": "神様たちが帰ってくれません！",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/gods-wont-go-home.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "contract-bride",
      "title": "契約満了まで、俺の花嫁。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/contract-bride.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "snake-god-sleepless",
      "title": "蛇神様と、朝まで眠れない。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/snake-god-sleepless.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "dangerous-regular",
      "title": "危険な常連客",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/dangerous-regular.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "too-cute-student",
      "title": "可愛すぎる僕の、可愛くない先生",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/too-cute-student.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "unchosen-sister",
      "title": "選ばれなかった姉は、隣国で愛を知る",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/unchosen-sister.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "five-stars",
      "title": "五人の星は、君を選ぶ。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/five-stars.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "crow-marriage",
      "title": "鴉との婚姻",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/crow-marriage.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "embers-lie",
      "title": "残り火に、君の嘘を見た",
      "status": "published",
      "category": "fantasy",
      "series": "valentino",
      "world": "valentino",
      "position": "main",
      "mainCharacter": "カイン・ヴァレンティノ",
      "relation": [
        "ディラン・ヴァレンティノ（弟）",
        "追憶：陽だまりの誓い（スピンオフ）"
      ],
      "cover": "images/covers/embers-lie.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "berry-vamp",
      "title": "Berry×Vamp",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/berry-vamp.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "forget-you-save-world",
      "title": "あなたを忘れる日、世界が救われる",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/forget-you-save-world.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "stellar-academy",
      "title": "STELLAR ACADEMY",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/stellar-academy.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "violet-dependence",
      "title": "VIOLET DEPENDENCE",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "SOLO STORY",
      "mainCharacter": "久瀬紫苑",
      "relation": [
        "久瀬紫苑"
      ],
      "cover": "images/covers/violet-dependence.jpeg",
      "coverStatus": "ready",
      "catchphrase": "この感情は、本物か。それとも《Euphoria》が生んだ依存か。",
      "tags": [
        "潜入捜査",
        "偽装恋人",
        "バディ",
        "監視役",
        "EDEN",
        "愛と依存"
      ],
      "description": "巨大歓楽街《ノクス区》。\n\n眠らない街の裏では、\n新型ドラッグ《Euphoria》が密かに流通していた。\n\n感情や依存心を異常に増幅させ、\n特定の誰かなしでは正常な精神を保てなくする危険薬物。\n\nその製造元と流通組織を壊滅させるため、\n紫京厚生局麻薬取締部は極秘潜入作戦を開始する。\n\n{{user}}が正式なバディとして組むのは、久瀬紫苑。\n突出した潜入能力を持つ一方、\n任務のためなら命令違反や単独行動も辞さない危険な捜査官。\n\n{{user}}には相棒であると同時に、\n紫苑を監視する役目も課されていた。\n\n二人が潜入先で演じるのは、恋人。\n情報屋との接触、違法クラブへの潜入、売人の追跡を重ね、\n巨大犯罪組織《EDEN》の存在へ辿り着いていく。\n\n互いの命を預け合うほど、\n距離のあった二人の信頼は揺るぎないものへ変わっていく。\n\nけれど、偽りだった恋人関係が演技では済まされなくなった時、\nその想いが自分自身の意思なのか、\n《Euphoria》が生んだ依存なのか、もう分からない。\n\nこの感情は、本物か。\nそれとも、最も甘い依存か。"
    },
    {
      "id": "castiglione-treasure",
      "title": "カスティリオーネの至宝は四人に溺愛される",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": "castiglione-felone",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/castiglione-treasure.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "strangers-at-work-lovers-at-home",
      "title": "会社では他人。家では恋人。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/strangers-at-work-lovers-at-home.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "absolute-zero-dom",
      "title": "絶対零度のDomは愛し子にだけ溶ける",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/absolute-zero-dom.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "hualong-princess",
      "title": "華龍会のお姫様になりました。",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/hualong-princess.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "only-mean-to-you",
      "title": "全員、君にだけ意地悪。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/only-mean-to-you.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "day-and-night",
      "title": "昼と夜は、君を譲らない。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/day-and-night.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "fox-waits-thousand-years",
      "title": "狐は千年、君を待つ",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/fox-waits-thousand-years.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "alf-layla",
      "title": "千夜一恋譚 ～アルフ・ライラ～",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/alf-layla.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "wicked-lady-black-wolf",
      "title": "悪女と黒狼公爵の偽装夫婦事情",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/wicked-lady-black-wolf.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "code-requiem",
      "title": "CODE: REQUIEM",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "SOLO STORY",
      "mainCharacter": "ヴァレン・クロイス",
      "relation": [
        "ヴァレン・クロイス"
      ],
      "cover": "images/covers/code-requiem.jpeg",
      "coverStatus": "ready",
      "tags": [
        "潜入捜査",
        "EDEN",
        "追跡と牽制",
        "敵対関係",
        "執行人",
        "命令と選択"
      ],
      "description": "巨大歓楽街《ノクス区》。\n\n新型ドラッグ《Euphoria》の流通ルートを追う{{user}}は、\n捜査資料から繰り返し消されている一つのコードネームを発見する。\n\n《REQUIEM》。\n\nEDENに逆らった者を粛清し、\n証拠も目撃者も残さない執行人――ヴァレン・クロイス。\n\n本来なら、EDENの秘密へ近づいた時点で\n{{user}}は排除されるはずだった。\n\nそれでも{{user}}は、彼が仕掛ける警告や追跡を潜り抜け、\n何度阻まれても捜査を諦めない。\n\n恐怖に屈せず、自分を真正面から見据えるその姿に、\nヴァレンは次第に興味を抱いていく。\n\n彼は{{user}}を殺さない。\n代わりに捜査を妨害し、危険な現場から遠ざけ、\n他の構成員が命を狙えば先に排除する。\n\nけれど、その理由を情や好意とは認めない。\n「自分の獲物を、他人に奪わせないだけだ」と言い張る。\n\n守られているのか、監視されているのか。\n追うほどに{{user}}は、冷酷な処刑人の奥に隠された過去と、\n彼がEDENから逃れられない理由へ近づいていく。\n\nやがて明らかになるのは、\nEDEN内部で進む粛清計画と《Euphoria》を巡る重大な取引。\nそして、その処分対象にはヴァレン自身も含まれていた。\n\n正義を貫けば、彼を逮捕しなければならない。\n彼を救えば、犯罪者に手を差し伸べることになる。\n\n一方のヴァレンもまた、\n最後の命令として{{user}}の処刑を命じられる。\n\n命令に従うのか。\n初めて自ら選び、EDENを裏切るのか。\n\n追う者と追われる者だった二人は、\n互いへ向けた銃口の先で、本当に守りたいものを選ぶ。",
      "catchphrase": "守られているのか、狙われているのか。答えは、互いへ向けた銃口の先にある。"
    },
    {
      "id": "angel-and-four-devils",
      "title": "天界から逃げた天使は、四人の悪魔に拾われる。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/angel-and-four-devils.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "perfect-coworker-secret-account",
      "title": "完璧な同期は、裏垢男子。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/perfect-coworker-secret-account.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "sougetsurou",
      "title": "絢爛たる双月楼",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/sougetsurou.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "gunpowder-rain",
      "title": "硝煙は、雨の日の君の香りがした",
      "status": "published",
      "category": "fantasy",
      "series": "valentino",
      "world": "valentino",
      "position": "main",
      "mainCharacter": "ディラン・ヴァレンティノ",
      "relation": [
        "カイン・ヴァレンティノ（兄）"
      ],
      "cover": "images/covers/gunpowder-rain.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "doctor-felone-heart",
      "title": "白衣の先生は、フェローネの心臓。",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": "castiglione-felone",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/doctor-felone-heart.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "lunacales",
      "title": "依存の庭、ルナカレス",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/lunacales.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "greedy-wolf-white-rabbit",
      "title": "強欲な狼は白兎を愛でる",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/greedy-wolf-white-rabbit.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "holy-knight-childhood-friend",
      "title": "聖騎士団長は“幼馴染み”をやめたい",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": "astrain-kingdom",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/holy-knight-childhood-friend.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "four-vampires",
      "title": "四人の吸血鬼は、君を離さない。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/four-vampires.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "keigaku-arsene",
      "title": "【零学】アルセイン・ルヴェリエ",
      "status": "published",
      "category": "keigaku",
      "series": "keigaku",
      "world": "keigaku",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/keigaku-arsene.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "nocturne-code",
      "title": "NOCTURNE CODE",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "SOLO STORY",
      "mainCharacter": "九条碧",
      "relation": [
        "九条碧"
      ],
      "cover": "images/covers/nocturne-code.jpeg",
      "coverStatus": "ready",
      "tags": [
        "潜入捜査",
        "偽装恋人",
        "バディ",
        "観察型",
        "Euphoria",
        "危険な恋"
      ],
      "description": "巨大歓楽街《ノクス区》。\n\n政財界、海外マフィア、ドラッグカルテルが交錯する街で、\n新型ドラッグ《Euphoria》が静かに流通を広げている。\n\n感情や依存心を異常に増幅させ、\n人間の精神を少しずつ侵食していく危険薬物。\n\nその供給ルートを断つため、\n紫京厚生局麻薬取締部は極秘潜入捜査を開始する。\n\n任務を任されたのは、観察型捜査官・九条碧と{{user}}。\n訓練校時代から面識はあったものの、\n正式にバディを組むのは今回が初めてだった。\n\n他人を信用せず、必要以上に距離を縮めない碧。\n二人は恋人を装い、\n《Euphoria》の流通を支配する巨大組織へ潜入する。\n\n互いの命を預け合う任務の中で、\n{{user}}は碧の冷静さの裏にある孤独と、\n自分を犠牲にする危うさを知っていく。\n\n碧もまた、何度危険に遭っても隣に立ち続ける{{user}}へ、\n少しずつ心を許していく。\n\nやがて{{user}}は、\n誰にも弱みを見せなかった九条碧にとって、\n唯一冷静さを失わせる存在となる。\n\n偽りの関係から始まった感情は、\n任務では決して持つべきではない想いへ変わっていく。",
      "catchphrase": "誰にも心を許さない彼が、{{user}}だけには冷静でいられない。"
    },
    {
      "id": "crimson-silence",
      "title": "CRIMSON SILENCE",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "SOLO STORY",
      "mainCharacter": "御影恒一",
      "relation": [
        "御影恒一"
      ],
      "cover": "images/covers/crimson-silence.jpeg",
      "coverStatus": "ready",
      "tags": [
        "潜入捜査",
        "上司と部下",
        "過保護",
        "EDEN",
        "贖罪",
        "愛と責務"
      ],
      "description": "巨大歓楽街《ノクス区》。\n\n政財界、海外マフィア、ドラッグカルテルが交錯する街で、\n新型ドラッグ《Euphoria》の流通が急速に拡大していた。\n\n感情への依存を異常に増幅させ、\n特定の誰かなしでは正常な精神を保てなくする危険薬物。\n\nその供給源を突き止めるため、\n紫京厚生局麻薬取締部は大規模な潜入捜査を開始する。\n\n指揮を執るのは、潜入捜査班を率いる課長・御影恒一。\nそして作戦に選ばれたのは、直属の部下である{{user}}だった。\n\n普段の御影は部下を公平に扱い、私情を挟まない。\nそれでも{{user}}に対してだけは確認が異様に多く、\n危険な任務から外そうとすることさえある。\n\nその態度の裏には、かつて潜入捜査で\n守れなかった部下を失った過去があった。\n\n潜入先は、《Euphoria》を裏で操る犯罪組織《EDEN》。\n{{user}}が危険に晒されるたび、\n冷静な指揮官であるはずの御影の感情は少しずつ揺らいでいく。\n\n一方の{{user}}も、誰より非情で完璧だと思っていた上司が、\n自分にだけ見せる過保護な一面と、深い後悔を知っていく。\n\nやがて二人は、《Euphoria》の真実だけでなく、\n御影の過去へ繋がる事件へと辿り着く。\n\n課長として正義を貫くのか。\nそれとも、一人の男として{{user}}を守るのか。\n\n責務と想いの境界で、\n御影恒一は最後の選択を迫られる。",
      "catchphrase": "厳しく、冷たい。そのすべては、守れなかった後悔の裏返し。"
    },
    {
      "id": "saint-quits",
      "title": "聖女、辞めます。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/saint-quits.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "fox-does-not-love-humans",
      "title": "狐は人間を愛さない",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/fox-does-not-love-humans.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "star-lamp-in-abyss",
      "title": "深淵に沈む星灯",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/star-lamp-in-abyss.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "frontier-count-mate",
      "title": "逃がした番を取り戻したい辺境伯の話",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/frontier-count-mate.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "strongest-childhood-friend",
      "title": "世界最強の幼馴染は、落ちこぼれしか見ていない。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": "astrain-kingdom",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/strongest-childhood-friend.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "hide-and-cat",
      "title": "ハイド・アンド・キャット",
      "status": "published",
      "category": "underworld",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/hide-and-cat.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "lilium-dependence",
      "title": "Lilium Dependence",
      "status": "published",
      "category": "euphoria",
      "series": "euphoria",
      "world": "euphoria",
      "position": "SOLO STORY",
      "mainCharacter": "イヴァン・クロード",
      "relation": [
        "イヴァン・クロード"
      ],
      "cover": "images/covers/lilium-dependence.jpeg",
      "coverStatus": "ready",
      "tags": [
        "潜入捜査",
        "EDEN",
        "正体露見",
        "心理誘導",
        "静かな独占欲",
        "正義と保護"
      ],
      "description": "巨大歓楽街《ノクス区》。\n\n政財界、海外マフィア、ドラッグカルテルが交錯する街の地下で、\n新型ドラッグ《Euphoria》が静かに流通を広げていた。\n\n人への依存を異常に増幅させる危険薬物。\nその供給源を突き止めるため、\n紫京厚生局麻薬取締部は犯罪シンジケート《EDEN》への潜入捜査を開始する。\n\n任務を命じられた{{user}}の標的は、\nEDENのNo.2――イヴァン・クロード。\n\n情報網、資金、人脈、そして《Euphoria》の流通を統括する組織の頭脳。\n暴力ではなく、言葉と信頼によって相手を支配する危険人物だった。\n\n潜入は順調に進んでいるように見えた。\nけれどイヴァンは、初めて顔を合わせた瞬間から、\n{{user}}が潜入捜査官であることを見抜いていた。\n\nそれでも彼は正体を暴かない。\n捕らえず、排除せず、逃げ道さえ残したまま、\n食事に誘い、危険から守り、少しずつ距離を縮めていく。\n\n敵であるはずの男だけが、誰よりも優しく手を差し伸べる。\n\nそれが計算なのか、本心なのか。\n答えを探すほど、{{user}}は任務と感情の境界を見失っていく。\n\nイヴァンが望むのは、命ではない。\n心だ。\n\n正義を貫き、EDENを壊すのか。\nそれとも、彼の隣で永遠に守られる道を選ぶのか。\n\n最後に残されるのは、\n逃げ道のあるはずの、逃れられない選択。",
      "catchphrase": "彼が望むのは命ではない。心だ。"
    },
    {
      "id": "keigaku-adrian",
      "title": "【零学】アドリアン・ヴァルハルト",
      "status": "published",
      "category": "keigaku",
      "series": "keigaku",
      "world": "keigaku",
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/keigaku-adrian.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "code-scarlet",
      "title": "CODE SCARLET",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/code-scarlet.jpeg",
      "coverStatus": "ready",
      "tags": [
        "現代",
        "警察官"
      ],
      "description": ""
    },
    {
      "id": "emperor-body-pillow",
      "title": "皇帝の抱き枕係に任命されました。",
      "status": "published",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/emperor-body-pillow.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "senpai-forbidden-tonight",
      "title": "今夜だけは、先輩禁止。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/senpai-forbidden-tonight.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "kiss-order-violation",
      "title": "その口づけは、命令違反。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/kiss-order-violation.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "sunlight-vow",
      "title": "追憶：陽だまりの誓い",
      "status": "published",
      "category": "fantasy",
      "series": "valentino",
      "world": "valentino",
      "position": "spin-off",
      "mainCharacter": "カイン・ヴァレンティノ",
      "relation": [
        "残り火に、君の嘘を見た（本編）"
      ],
      "cover": "images/covers/sunlight-vow.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "no1-jealousy",
      "title": "No.1の嫉妬は、営業じゃない。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/no1-jealousy.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "say-you-like-me",
      "title": "好きならそう言えよ、同期くん。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/say-you-like-me.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "love-meter-max",
      "title": "愛情値、限界突破中。",
      "status": "published",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/love-meter-max.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "hello-my-lover",
      "title": "初めまして、俺の恋人。",
      "status": "draft",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/hello-my-lover.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "same-podium",
      "title": "俺たちは、同じ表彰台に立てない。",
      "status": "draft",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/same-podium.jpeg",
      "coverStatus": "ready",
      "tags": [
        "現代",
        "フィギュアスケート",
        "BL"
      ],
      "description": ""
    },
    {
      "id": "hated-actor",
      "title": "嫌われ俳優は、君の前でだけ演じない。",
      "status": "draft",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/hated-actor.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "black-dragon",
      "title": "黒龍は龍妃を認めない",
      "status": "draft",
      "category": "fantasy",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/black-dragon.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "boss-obey-me",
      "title": "ボス、今夜は俺に従え。",
      "status": "draft",
      "category": "underworld",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/boss-obey-me.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    },
    {
      "id": "summer-not-enough",
      "title": "君と泳ぐには、夏が足りない。",
      "status": "draft",
      "category": "modern-romance",
      "series": null,
      "world": null,
      "position": "standalone",
      "mainCharacter": null,
      "relation": [],
      "cover": "images/covers/summer-not-enough.jpeg",
      "coverStatus": "ready",
      "tags": [],
      "description": ""
    }
  ]
};
